spring:
  kafka:
    bootstrap-servers: {{ kafka.broker.server }}
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='{{ CLUSTER API KEY }}' password='{{ CLUSTER API SECRET }}';
        mechanism: PLAIN
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
